// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Falkan ama file-kan waxaa soo saaray FlutterFire CLI (Auto-generated).
/// Waxay ka kooban tahay furayaasha (API Keys) loo baahan yahay si abka loogu xiro Firebase.
/// Waxay kala saartaa habaynta u gaarka ah Android, iOS, Web, iyo qalabka kale.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web configuration not found. Run "flutterfire configure" to generate.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS configuration not found. Run "flutterfire configure" to generate.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS configuration not found. Run "flutterfire configure" to generate.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows configuration not found. Run "flutterfire configure" to generate.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux configuration not found. Run "flutterfire configure" to generate.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeZ9oQ_zlBL2BRediEVc1YxRBpekn2KkE',
    appId: '1:927675711622:android:7863acfa317b1f6cbad107',
    messagingSenderId: '927675711622',
    projectId: 'barberapp-b5f16',
    storageBucket: 'barberapp-b5f16.firebasestorage.app',
  );
}
